### ISSUE TITLE
Running on docker logs 

### ISSUE THREAD

**Issue by kiddingl** [WeblateOrg/docker#284] opened 2019-07-03 08:04 UTC
Errors:

ERROR Handled exception: OperationalError: cannot ALTER TABLE "trans_vote" because it has pending trigger events

--------
My weblate is not running

**Comment by nijel** [comment] 2019-07-03 11:26
Duplicate of https://github.com/WeblateOrg/weblate/issues/2851

**Closed by nijel** 2019-07-03 11:26 UTC

**Comment by nijel** [comment] 2019-07-04 08:14
Thank you for your report, the issue you have reported has just been fixed in 3.7.1-3. 

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).
