### ISSUE TITLE
Weblate container fails to start with Docker containerd experimental option enabled

### ISSUE THREAD

**Issue by cvb941** [WeblateOrg/docker#1840] opened 2023-05-22 07:08 UTC
### Describe the issue

Weblate container fails with permission issue:
`mkdir: cannot create directory '/run': Permission denied`

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar issues in this repository.

### Steps to reproduce the behavior

1. Enable use containerd experimental setting in Docker Desktop settings
2. Start docker compose
3. Weblate container fails to start

### Additional context

Docker running on MacOS

**Comment by nijel** [comment] 2023-05-25 09:28
Which setting? Read only filesystem? That would be duplicate of https://github.com/WeblateOrg/docker/issues/1831

**Comment by cvb941** [comment] 2023-05-25 16:27
It is this experimental setting in Docker Desktop.
<img width="1270" alt="Screenshot 2023-05-25 at 18 25 26" src="https://github.com/WeblateOrg/docker/assets/2351527/e344aaff-7cd5-4f85-af56-a95b679ae614">

**Comment by nijel** [comment] 2023-05-29 11:26
Okay, that really explains nothing – it talks about pulling and storing images, not about execution of the containers.

Anyway, the error message is the same, so let's assume the cause is the same as well. If you have information that would indicate otherwise, please let us know.

**Comment by nijel** [comment] 2023-05-29 11:26
Duplicate of #1831

**Closed by nijel** 2023-05-29 11:26 UTC
Labels: duplicate, enhancement
