### ISSUE TITLE
Cannot generate GPG key after setting WEBLATE_GPG_IDENTITY

### ISSUE THREAD

**Issue by JonahAragon** [WeblateOrg/docker#456] opened 2019-11-26 08:01 UTC
`gpg` does not appear to be installed in my Docker container:

```
[Errno 2] No such file or directory: 'gpg': 'gpg'
```

I've set `WEBLATE_GPG_IDENTITY` in `/app/data/settings-override.py`

**Comment by nijel** [comment] 2019-11-26 11:19
Maybe you're using old container? It was added in d683f87a

Duplicate of #278

**Closed by nijel** 2019-11-26 11:19 UTC
