### ISSUE TITLE
Missing dependency on arm64 platform (image tag 5)

### ISSUE THREAD

**Issue by eltorio** [WeblateOrg/docker#1971] opened 2023-09-13 07:15 UTC
### Describe the issue

While running inside an arm64 1.28.1 kubernetes cluser, the container crash because libtesseract.so.4 is missing

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar issues in this repository.

### Steps to reproduce the behavior

1 install in K8S with
```bash
  helm repo add weblate https://helm.weblate.org
  helm repo update weblate
  cat <<EOF >/tmp/weblate.yaml
debug: '1'
persistence:
  size: 10Gi
  accessMode: ReadWriteMany
image:
  tag: '5'
replicaCount: 2
adminEmail: '$WEBLATE_EMAIL'
adminUser: '$WEBLATE_ADMIN'
adminPassword: '$WEBLATE_PASSWORD'
siteDomain: 'weblate.$AZURE_DNS_ZONE'
defaultFromEmail: '$WEBLATE_EMAIL_SENDER'
emailHost: '$WEBLATE_EMAIL_SENDER_HOST'
emailPassword: '$WEBLATE_EMAIL_SENDER_PASSWORD'
emailUser: '$WEBLATE_EMAIL_SENDER'
serverEmail: $WEBLATE_EMAIL_SENDER'
configOverride: |
  REGISTRATION_EMAIL_MATCH = $WEBLATE_REGISTRATION_EMAIL_MATCH
  WEBLATE_GPG_IDENTITY = "$WEBLATE_GPG_IDENTITY"
  ENABLE_HTTPS = True
  SESSION_COOKIE_SECURE = ENABLE_HTTPS
  SECURE_SSL_REDIRECT = ENABLE_HTTPS
  SECURE_HSTS_PRELOAD = ENABLE_HTTPS
  SECURE_HSTS_INCLUDE_SUBDOMAINS = ENABLE_HTTPS
  SECURE_HSTS_SECONDS = 3600
  BORG_EXTRA_ARGS = ["--exclude", "lost+found","--exclude", "/app/data/lost+found"]
emailSSL: false
emailTLS: true
livenessProbe:
  initialDelaySeconds: 120
ingress:
  enabled: true
  ingressClassName: haproxy
  annotations:
    cert-manager.io/cluster-issuer:  letsencrypt-azure #$CA_COMPANY-ca-issuer
  hosts:
  - host: weblate.$AZURE_DNS_ZONE
    paths:
    - path: /
      pathType: Prefix
  tls:
     - secretName: weblate-tls
       hosts:
         - weblate.$AZURE_DNS_ZONE
EOF
  helm $METHOD --namespace weblate --create-namespace weblate weblate/weblate --values /tmp/weblate.yaml
```

### Expected behavior

Running

### Exception traceback

```pytb
2023-09-13T07:09:08.002911324Z Starting...
2023-09-13T07:09:10.763631797Z [2023-09-13 07:09:10,763: WARNING/10] Handled exception: ImportError: libtesseract.so.4: cannot open shared object file: No such file or directory
2023-09-13T07:09:10.763674477Z Traceback (most recent call last):
2023-09-13T07:09:10.763677877Z   File "/usr/local/bin/weblate", line 8, in <module>
2023-09-13T07:09:10.763805598Z     sys.exit(main())
2023-09-13T07:09:10.764203319Z              ^^^^^^
2023-09-13T07:09:10.764236760Z   File "/usr/local/lib/python3.11/site-packages/weblate/runner.py", line 19, in main
2023-09-13T07:09:10.764387560Z     utility.execute()
2023-09-13T07:09:10.764433240Z   File "/usr/local/lib/python3.11/site-packages/django/core/management/__init__.py", line 436, in execute
2023-09-13T07:09:10.764609121Z     self.fetch_command(subcommand).run_from_argv(self.argv)
2023-09-13T07:09:10.764668401Z   File "/usr/local/lib/python3.11/site-packages/django/core/management/base.py", line 412, in run_from_argv
2023-09-13T07:09:10.764861482Z     self.execute(*args, **cmd_options)
2023-09-13T07:09:10.764916082Z   File "/usr/local/lib/python3.11/site-packages/django/core/management/base.py", line 458, in execute
2023-09-13T07:09:10.765085403Z     output = self.handle(*args, **options)
2023-09-13T07:09:10.765905246Z              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-09-13T07:09:10.765921886Z   File "/usr/local/lib/python3.11/site-packages/django/core/management/commands/check.py", line 76, in handle
2023-09-13T07:09:10.766096447Z     self.check(
2023-09-13T07:09:10.766123047Z   File "/usr/local/lib/python3.11/site-packages/django/core/management/base.py", line 485, in check
2023-09-13T07:09:10.766308408Z     all_issues = checks.run_checks(
2023-09-13T07:09:10.773440796Z                  ^^^^^^^^^^^^^^^^^^
2023-09-13T07:09:10.773461916Z   File "/usr/local/lib/python3.11/site-packages/django/core/checks/registry.py", line 88, in run_checks
2023-09-13T07:09:10.773465636Z     new_errors = check(app_configs=app_configs, databases=databases)
2023-09-13T07:09:10.773468156Z                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-09-13T07:09:10.773470316Z   File "/usr/local/lib/python3.11/site-packages/django/core/checks/urls.py", line 14, in check_url_config
2023-09-13T07:09:10.773472436Z     return check_resolver(resolver)
2023-09-13T07:09:10.773474516Z            ^^^^^^^^^^^^^^^^^^^^^^^^
2023-09-13T07:09:10.773476636Z   File "/usr/local/lib/python3.11/site-packages/django/core/checks/urls.py", line 24, in check_resolver
2023-09-13T07:09:10.773492516Z     return check_method()
2023-09-13T07:09:10.773497516Z            ^^^^^^^^^^^^^^
2023-09-13T07:09:10.773500116Z   File "/usr/local/lib/python3.11/site-packages/django/urls/resolvers.py", line 494, in check
2023-09-13T07:09:10.773502436Z     for pattern in self.url_patterns:
2023-09-13T07:09:10.773504716Z                    ^^^^^^^^^^^^^^^^^
2023-09-13T07:09:10.773506756Z   File "/usr/local/lib/python3.11/site-packages/django/utils/functional.py", line 57, in __get__
2023-09-13T07:09:10.773509116Z     res = instance.__dict__[self.name] = self.func(instance)
2023-09-13T07:09:10.773511196Z                                          ^^^^^^^^^^^^^^^^^^^
2023-09-13T07:09:10.773513236Z   File "/usr/local/lib/python3.11/site-packages/django/urls/resolvers.py", line 715, in url_patterns
2023-09-13T07:09:10.773515636Z     patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
2023-09-13T07:09:10.773517756Z                        ^^^^^^^^^^^^^^^^^^^
2023-09-13T07:09:10.773519756Z   File "/usr/local/lib/python3.11/site-packages/django/utils/functional.py", line 57, in __get__
2023-09-13T07:09:10.773521796Z     res = instance.__dict__[self.name] = self.func(instance)
2023-09-13T07:09:10.773539876Z                                          ^^^^^^^^^^^^^^^^^^^
2023-09-13T07:09:10.773542196Z   File "/usr/local/lib/python3.11/site-packages/django/urls/resolvers.py", line 708, in urlconf_module
2023-09-13T07:09:10.773544196Z     return import_module(self.urlconf_name)
2023-09-13T07:09:10.773546156Z            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-09-13T07:09:10.773548116Z   File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
2023-09-13T07:09:10.773550116Z     return _bootstrap._gcd_import(name[level:], package, level)
2023-09-13T07:09:10.773552076Z            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-09-13T07:09:10.773554036Z   File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
2023-09-13T07:09:10.773555996Z   File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
2023-09-13T07:09:10.773557956Z   File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
2023-09-13T07:09:10.773559956Z   File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
2023-09-13T07:09:10.773561996Z   File "<frozen importlib._bootstrap_external>", line 940, in exec_module
2023-09-13T07:09:10.773563956Z   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
2023-09-13T07:09:10.773565956Z   File "/usr/local/lib/python3.11/site-packages/weblate/urls.py", line 25, in <module>
2023-09-13T07:09:10.773567916Z     import weblate.screenshots.views
2023-09-13T07:09:10.773570076Z   File "/usr/local/lib/python3.11/site-packages/weblate/screenshots/views.py", line 39, in <module>
2023-09-13T07:09:10.773572076Z     from tesserocr import OEM, PSM, RIL, PyTessBaseAPI, iterate_level
2023-09-13T07:09:10.773574036Z ImportError: libtesseract.so.4: cannot open shared object file: No such file or directory
2023-09-13T07:09:11.321794556Z Failed to load configuration, please see errors above.
```

**Comment by nijel** [comment] 2023-09-13 09:06
Duplicate of #1944

**Comment by nijel** [comment] 2023-09-13 09:06
Probably you fetched 5 tag before the fix and did not update since then?

**Closed by nijel** 2023-09-13 09:06 UTC
Labels: bug, duplicate

**Comment by eltorio** [comment] 2023-09-13 09:09
no I tried today… it is maybe a docker hub cache… I'll force to use the tag 5.0.1.1

**Comment by nijel** [comment] 2023-09-13 09:19
5.0.1.1 and 5 should be the same images (https://hub.docker.com/r/weblate/weblate/tags confirms that). But you should use `pullPolicy: Always` for moving tags like this; otherwise Kubernetes will never pull it again.
