### ISSUE TITLE
Translating issues

### ISSUE THREAD

**Issue by thecraftman** [WeblateOrg/docker#688] opened 2020-06-12 13:29 UTC
I  am hosting Weblate locally with docker & docker-compose. I ran the docker commands and it worked. I can access weblate from localhost. The issue here is i can't translate from one language to another.  

when i try to add translated languages i can't see other languages. even when adding projects i can't specify the language for it to be translated to. it outputs the error `nothing to list here` . 

is there a workflow for  translation using docker-compose ?

Thanks. @nijel

**Comment by nijel** [comment] 2020-06-12 13:47
Duplicate of #687

**Closed by nijel** 2020-06-12 13:47 UTC
Labels: duplicate
