### ISSUE TITLE
Failure while executing task: FieldError: Cannot resolve keyword 'expires' into field

### ISSUE THREAD

**Issue by szjozsef** [WeblateOrg/docker#1431] opened 2022-03-18 14:24 UTC
### Describe the issue

Weblate seems to run correctly using the latest docker image, however there are some errors logged in console / sentry

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar issues in this repository.

### Steps to reproduce the behavior

check the console of the docker image

### Expected behavior

no errors should be present

### Exception traceback

```pytb
celery-celery stderr | [2022-03-18 15:58:25,101: ERROR/340] Failure while executing task: FieldError: Cannot resolve keyword 'expires' into field. Choices are: auditlog, auth_token, author_set, change, comment, contributoragreement, date_expires, date_joined, email, font, full_name, groups, id, is_active, is_bot, is_superuser, last_login, logentry, memory, password, profile, screenshot, social_auth, subscription, suggestion, user_votes, userblock, username, vote
celery-celery stderr | [2022-03-18 15:58:25,101: ERROR/ForkPoolWorker-3] Failure while executing task: FieldError: Cannot resolve keyword 'expires' into field. Choices are: auditlog, auth_token, author_set, change, comment, contributoragreement, date_expires, date_joined, email, font, full_name, groups, id, is_active, is_bot, is_superuser, last_login, logentry, memory, password, profile, screenshot, social_auth, subscription, suggestion, user_votes, userblock, username, vote
celery-celery stderr | [2022-03-18 15:58:25,101: ERROR/340] Failure while executing task: FieldError: {'signal': <Signal: task_failure providing_args={'task_id', 'exception', 'einfo', 'args', 'traceback', 'kwargs'}>, 'sender': <@task: weblate.auth.tasks.disable_expired of weblate at 0x7f95cacad120>, 'task_id': 'ca289bce-a572-4b48-aa63-7cf390388246', 'args': [], 'kwargs': {}, 'traceback': <traceback object at 0x7f95c08daf80>, 'einfo': <ExceptionInfo: FieldError("Cannot resolve keyword 'expires' into field. Choices are: auditlog, auth_token, author_set, change, comment, contributoragreement, date_expires, date_joined, email, font, full_name, groups, id, is_active, is_bot, is_superuser, last_login, logentry, memory, password, profile, screenshot, social_auth, subscription, suggestion, user_votes, userblock, username, vote")>}
celery-celery stderr | [2022-03-18 15:58:25,101: ERROR/ForkPoolWorker-3] Failure while executing task: FieldError: {'signal': <Signal: task_failure providing_args={'task_id', 'exception', 'einfo', 'args', 'traceback', 'kwargs'}>, 'sender': <@task: weblate.auth.tasks.disable_expired of weblate at 0x7f95cacad120>, 'task_id': 'ca289bce-a572-4b48-aa63-7cf390388246', 'args': [], 'kwargs': {}, 'traceback': <traceback object at 0x7f95c08daf80>, 'einfo': <ExceptionInfo: FieldError("Cannot resolve keyword 'expires' into field. Choices are: auditlog, auth_token, author_set, change, comment, contributoragreement, date_expires, date_joined, email, font, full_name, groups, id, is_active, is_bot, is_superuser, last_login, logentry, memory, password, profile, screenshot, social_auth, subscription, suggestion, user_votes, userblock, username, vote")>}
celery-celery stderr | [2022-03-18 15:58:25,101: ERROR/340] Failure while executing task
celery-celery stderr | Traceback (most recent call last):
celery-celery stderr |   File "/usr/local/lib/python3.10/site-packages/celery/app/trace.py", line 451, in trace_task
celery-celery stderr |     R = retval = fun(*args, **kwargs)
celery-celery stderr |   File "/usr/local/lib/python3.10/site-packages/sentry_sdk/integrations/celery.py", line 200, in _inner
celery-celery stderr |     reraise(*exc_info)
celery-celery stderr |   File "/usr/local/lib/python3.10/site-packages/sentry_sdk/_compat.py", line 54, in reraise
celery-celery stderr |     raise value
celery-celery stderr |   File "/usr/local/lib/python3.10/site-packages/sentry_sdk/integrations/celery.py", line 195, in _inner
celery-celery stderr |     return f(*args, **kwargs)
celery-celery stderr |   File "/usr/local/lib/python3.10/site-packages/celery/app/trace.py", line 734, in __protected_call__
celery-celery stderr |     return self.run(*args, **kwargs)
celery-celery stderr |   File "/usr/local/lib/python3.10/site-packages/weblate/auth/tasks.py", line 28, in disable_expired
celery-celery stderr |     User.objects.filter(expires__lte=timezone.now(), is_active=True).update(
celery-celery stderr |   File "/usr/local/lib/python3.10/site-packages/django/db/models/manager.py", line 85, in manager_method
celery-celery stderr |     return getattr(self.get_queryset(), name)(*args, **kwargs)
celery-celery stderr |   File "/usr/local/lib/python3.10/site-packages/django/db/models/query.py", line 1071, in filter
celery-celery stderr |     return self._filter_or_exclude(False, args, kwargs)
celery-celery stderr |   File "/usr/local/lib/python3.10/site-packages/django/db/models/query.py", line 1089, in _filter_or_exclude
celery-celery stderr |     clone._filter_or_exclude_inplace(negate, args, kwargs)
celery-celery stderr |   File "/usr/local/lib/python3.10/site-packages/django/db/models/query.py", line 1096, in _filter_or_exclude_inplace
celery-celery stderr |     self._query.add_q(Q(*args, **kwargs))
celery-celery stderr |   File "/usr/local/lib/python3.10/site-packages/django/db/models/sql/query.py", line 1466, in add_q
celery-celery stderr |     clause, _ = self._add_q(q_object, self.used_aliases)
celery-celery stderr |   File "/usr/local/lib/python3.10/site-packages/django/db/models/sql/query.py", line 1496, in _add_q
celery-celery stderr |     child_clause, needed_inner = self.build_filter(
celery-celery stderr |   File "/usr/local/lib/python3.10/site-packages/django/db/models/sql/query.py", line 1342, in build_filter
celery-celery stderr |     lookups, parts, reffed_expression = self.solve_lookup_type(arg)
celery-celery stderr |   File "/usr/local/lib/python3.10/site-packages/django/db/models/sql/query.py", line 1156, in solve_lookup_type
celery-celery stderr |     _, field, _, lookup_parts = self.names_to_path(lookup_splitted, self.get_meta())
celery-celery stderr |   File "/usr/local/lib/python3.10/site-packages/django/db/models/sql/query.py", line 1640, in names_to_path
celery-celery stderr |     raise FieldError(
celery-celery stderr | django.core.exceptions.FieldError: Cannot resolve keyword 'expires' into field. Choices are: auditlog, auth_token, author_set, change, comment, contributoragreement, date_expires, date_joined, email, font, full_name, groups, id, is_active, is_bot, is_superuser, last_login, logentry, memory, password, profile, screenshot, social_auth, subscription, suggestion, user_votes, userblock, username, vote
celery-celery stderr | [2022-03-18 15:58:25,101: ERROR/ForkPoolWorker-3] Failure while executing task
celery-celery stderr | Traceback (most recent call last):
celery-celery stderr |   File "/usr/local/lib/python3.10/site-packages/celery/app/trace.py", line 451, in trace_task
celery-celery stderr |     R = retval = fun(*args, **kwargs)
celery-celery stderr |   File "/usr/local/lib/python3.10/site-packages/sentry_sdk/integrations/celery.py", line 200, in _inner
celery-celery stderr |     reraise(*exc_info)
celery-celery stderr |   File "/usr/local/lib/python3.10/site-packages/sentry_sdk/_compat.py", line 54, in reraise
celery-celery stderr |     raise value
celery-celery stderr |   File "/usr/local/lib/python3.10/site-packages/sentry_sdk/integrations/celery.py", line 195, in _inner
celery-celery stderr |     return f(*args, **kwargs)
celery-celery stderr |   File "/usr/local/lib/python3.10/site-packages/celery/app/trace.py", line 734, in __protected_call__
celery-celery stderr |     return self.run(*args, **kwargs)
celery-celery stderr |   File "/usr/local/lib/python3.10/site-packages/weblate/auth/tasks.py", line 28, in disable_expired
celery-celery stderr |     User.objects.filter(expires__lte=timezone.now(), is_active=True).update(
celery-celery stderr |   File "/usr/local/lib/python3.10/site-packages/django/db/models/manager.py", line 85, in manager_method
celery-celery stderr |     return getattr(self.get_queryset(), name)(*args, **kwargs)
celery-celery stderr |   File "/usr/local/lib/python3.10/site-packages/django/db/models/query.py", line 1071, in filter
celery-celery stderr |     return self._filter_or_exclude(False, args, kwargs)
celery-celery stderr |   File "/usr/local/lib/python3.10/site-packages/django/db/models/query.py", line 1089, in _filter_or_exclude
celery-celery stderr |     clone._filter_or_exclude_inplace(negate, args, kwargs)
celery-celery stderr |   File "/usr/local/lib/python3.10/site-packages/django/db/models/query.py", line 1096, in _filter_or_exclude_inplace
celery-celery stderr |     self._query.add_q(Q(*args, **kwargs))
celery-celery stderr |   File "/usr/local/lib/python3.10/site-packages/django/db/models/sql/query.py", line 1466, in add_q
celery-celery stderr |     clause, _ = self._add_q(q_object, self.used_aliases)
celery-celery stderr |   File "/usr/local/lib/python3.10/site-packages/django/db/models/sql/query.py", line 1496, in _add_q
celery-celery stderr |     child_clause, needed_inner = self.build_filter(
celery-celery stderr |   File "/usr/local/lib/python3.10/site-packages/django/db/models/sql/query.py", line 1342, in build_filter
celery-celery stderr |     lookups, parts, reffed_expression = self.solve_lookup_type(arg)
celery-celery stderr |   File "/usr/local/lib/python3.10/site-packages/django/db/models/sql/query.py", line 1156, in solve_lookup_type
celery-celery stderr |     _, field, _, lookup_parts = self.names_to_path(lookup_splitted, self.get_meta())
celery-celery stderr |   File "/usr/local/lib/python3.10/site-packages/django/db/models/sql/query.py", line 1640, in names_to_path
celery-celery stderr |     raise FieldError(
celery-celery stderr | django.core.exceptions.FieldError: Cannot resolve keyword 'expires' into field. Choices are: auditlog, auth_token, author_set, change, comment, contributoragreement, date_expires, date_joined, email, font, full_name, groups, id, is_active, is_bot, is_superuser, last_login, logentry, memory, password, profile, screenshot, social_auth, subscription, suggestion, user_votes, userblock, username, vote
```

**Comment by nijel** [comment] 2022-03-24 13:35
Duplicate of https://github.com/WeblateOrg/weblate/issues/7385

**Closed by nijel** 2022-03-24 13:35 UTC
Labels: bug, duplicate
