### ISSUE TITLE
weblate.E003: Email configuration error due to missing dependencies

### ISSUE THREAD

**Issue by lyz-code** [WeblateOrg/docker#697] opened 2020-06-17 10:26 UTC
Hi, I'm having issues when deploying weblate into kubernetes as the email is not working.

```
weblate.E003 	Cannot send e-mail ([Errno -2] Name or service not known), please check EMAIL_* settings.
```

I've tried using the `sendtestemail` command from within the docker but got the warning that the initparse library is not present.

```bash
weblate@weblate-69c555d8fc-bzp7l:/$ weblate sendtestemail someemail@domain.org
System check identified some issues:

WARNINGS:
?: (weblate.W025.ini) Failure in loading handler for ini file format: Missing iniparse library.
	HINT: https://docs.weblate.org/en/weblate-4.1/admin/install.html#optional-deps
?: (weblate.W025.islu) Failure in loading handler for islu file format: Missing iniparse library.
	HINT: https://docs.weblate.org/en/weblate-4.1/admin/install.html#optional-deps
WARNING Handled exception: gaierror: [Errno -2] Name or service not known
...

weblate@weblate-69c555d8fc-bzp7l:/$ env | grep -i mail:
WEBLATE_ADMIN_EMAIL=someemail@domain.org
WEBLATE_EMAIL_HOST=smtp.somedomain.org:25
WEBLATE_EMAIL_PASSWORD=somepassword
WEBLATE_EMAIL_USER=someemail@domain.org
WEBLATE_SERVER_EMAIL=someemail@domain.org
WEBLATE_DEFAULT_FROM_EMAIL=someemail@domain.org

weblate@weblate-69c555d8fc-bzp7l:/$ curl http://smtp.somedomain.org:25
220 smtp.somedomain.org SMTP MailServer
221 Error: Some mailserver error
```

So I've checked the following:

* The environmental variables are set.
* The container has network connectivity and can resolve the smtp server endpoint.
* I've got other services in the cluster that use the same smtp server, and they work correctly.

Therefore the only thing I can think of is that the `initparse` dependency is what's preventing it to work.

Any ideas? 

Thanks

**Comment by nijel** [comment] 2020-06-17 10:34
Please upgrade :-). The iniparse dependency is already fixed by https://github.com/WeblateOrg/docker/commit/2d8b113f32fa1cba4646f4ace56c86c6688153c7

Anyway this is just a warning, the error is still there:

> WARNING Handled exception: gaierror: [Errno -2] Name or service not known

I think the problem is in including port in `WEBLATE_EMAIL_HOST`. In case you need (what is not the case for default one), use `WEBLATE_EMAIL_PORT`.

**Closed by nijel** 2020-06-17 10:34 UTC
Labels: bug
