### ISSUE TITLE
docker-compose up failing

### ISSUE THREAD

**Issue by ToxicTree** [WeblateOrg/docker#147] opened 2019-02-21 10:51 UTC
We are having problems with the docker image. We had to restart some containers a few weeks ago and noticed that weblate is restarting every 15 seconds while on, making it impossible to use the platform.
The installation was made **2018-11-08** with the guide on your homepage: https://docs.weblate.org/en/latest/admin/deployments.html#docker

This is the output we get every time the weblate container fails and restart:
```weblate_1   | Postgres is up
weblate_1   | Operations to perform:
weblate_1   |   Apply all migrations: accounts, addons, admin, auth, authtoken, checks, contenttypes, gitexport, lang, memory, screenshots, sessions, sites, social_django, trans, weblate_auth, wladmin
weblate_1   | Running migrations:
weblate_1   |   No migrations to apply.
weblate_1   | ERROR Handled exception TypeError: unsupported format string passed to error.__format__
weblate_1   | Traceback (most recent call last):
weblate_1   |   File "/usr/lib/python3.6/shelve.py", line 111, in __getitem__
weblate_1   |     value = self.cache[key]
weblate_1   | KeyError: 'entries'
weblate_1   |
weblate_1   | During handling of the above exception, another exception occurred:
weblate_1   |
weblate_1   | Traceback (most recent call last):
weblate_1   |   File "/usr/local/lib/python3.6/dist-packages/celery/beat.py", line 515, in _create_schedule
weblate_1   |     self._store[str('entries')]
weblate_1   |   File "/usr/lib/python3.6/shelve.py", line 113, in __getitem__
weblate_1   |     f = BytesIO(self.dict[key.encode(self.keyencoding)])
weblate_1   | KeyError: b'entries'
weblate_1   |
weblate_1   | During handling of the above exception, another exception occurred:
weblate_1   |
weblate_1   | Traceback (most recent call last):
weblate_1   |   File "/usr/local/lib/python3.6/dist-packages/weblate/utils/management/commands/cleanup_celery.py", line 36, in handle
weblate_1   |     app=app
weblate_1   |   File "/usr/local/lib/python3.6/dist-packages/celery/beat.py", line 458, in __init__
weblate_1   |     Scheduler.__init__(self, *args, **kwargs)
weblate_1   |   File "/usr/local/lib/python3.6/dist-packages/celery/beat.py", line 225, in __init__
weblate_1   |     self.setup_schedule()
weblate_1   |   File "/usr/local/lib/python3.6/dist-packages/celery/beat.py", line 486, in setup_schedule
weblate_1   |     self._create_schedule()
weblate_1   |   File "/usr/local/lib/python3.6/dist-packages/celery/beat.py", line 519, in _create_schedule
weblate_1   |     self._store[str('entries')] = {}
weblate_1   |   File "/usr/lib/python3.6/shelve.py", line 125, in __setitem__
weblate_1   |     self.dict[key.encode(self.keyencoding)] = f.getvalue()
weblate_1   | _dbm.error: cannot add item to database
weblate_1   |
weblate_1   | During handling of the above exception, another exception occurred:
weblate_1   |
weblate_1   | Traceback (most recent call last):
weblate_1   |   File "/usr/local/bin/weblate", line 11, in <module>
weblate_1   |     sys.exit(main())
weblate_1   |   File "/usr/local/lib/python3.6/dist-packages/weblate/runner.py", line 34, in main
weblate_1   |     execute_from_command_line(argv)
weblate_1   |   File "/usr/local/lib/python3.6/dist-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
weblate_1   |     utility.execute()
weblate_1   |   File "/usr/local/lib/python3.6/dist-packages/django/core/management/__init__.py", line 375, in execute
weblate_1   |     self.fetch_command(subcommand).run_from_argv(self.argv)
weblate_1   |   File "/usr/local/lib/python3.6/dist-packages/django/core/management/base.py", line 316, in run_from_argv
weblate_1   |     self.execute(*args, **cmd_options)
weblate_1   |   File "/usr/local/lib/python3.6/dist-packages/django/core/management/base.py", line 353, in execute
weblate_1   |     output = self.handle(*args, **options)
weblate_1   |   File "/usr/local/lib/python3.6/dist-packages/weblate/utils/management/commands/cleanup_celery.py", line 41, in handle
weblate_1   |     'Removing corrupted schedule file: {:r}'.format(error)
weblate_1   | TypeError: unsupported format string passed to error.__format__
weblate_1   | Exception ignored in: <bound method Shelf.__del__ of <shelve.DbfilenameShelf object at 0x7f0e2f9d8c88>>
weblate_1   | Traceback (most recent call last):
weblate_1   |   File "/usr/lib/python3.6/shelve.py", line 162, in __del__
weblate_1   |     self.close()
weblate_1   |   File "/usr/lib/python3.6/shelve.py", line 144, in close
weblate_1   |     self.sync()
weblate_1   |   File "/usr/lib/python3.6/shelve.py", line 168, in sync
weblate_1   |     self[key] = entry
weblate_1   |   File "/usr/lib/python3.6/shelve.py", line 125, in __setitem__
weblate_1   |     self.dict[key.encode(self.keyencoding)] = f.getvalue()
weblate_1   | _dbm.error: cannot add item to database
weblatedocker_weblate_1 exited with code 1
```

Configuration: (docker-compose.yml)
```version: '3.1'
services:
  weblate:
    image: weblate/weblate
    ports:
      - 8011:80
    volumes:
      - weblate-data:/app/data
    env_file:
      - ./environment
    restart: always
    depends_on:
      - database
      - cache
  database:
    image: postgres:9.6-alpine
    env_file:
      - ./environment
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: always
  cache:
    image: redis:4-alpine
    restart: always
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis-data:/data
volumes:
  weblate-data: {}
  postgres-data: {}
  redis-data: {}
```

Versions: (docker-compose run --rm weblate list_versions)
``` * Weblate 3.4
 * Python 3.6.7
 * Django 2.1.5
 * Celery 4.2.1
 * celery-batches 0.2
 * six 1.12.0
 * social-auth-core 3.0.0
 * social-auth-app-django 3.1.0
 * django-appconf 1.0.2
 * translate-toolkit 2.3.1
 * translation-finder 1.0
 * Whoosh 2.7.4
 * defusedxml 0.5.0
 * Git 2.17.1
 * Pillow 5.1.0
 * python-dateutil 2.7.5
 * lxml 4.2.1
 * django-crispy-forms 1.7.2
 * django_compressor 2.2
 * djangorestframework 3.9.1
 * user-agents 1.1.0
 * jellyfish 0.7.1
 * diff-match-patch 20121119
 * pytz 2018.9
 * pyuca 1.2
 * PyYAML 3.12
 * tesserocr 2.4.0
 * Mercurial 4.5.3
 * git-svn 2.17.1
 * Database backends: django.db.backends.postgresql
 * Cache backends: avatar:FileBasedCache, default:RedisCache
 * Celery: redis://cache:6379/1, redis://cache:6379/1, regular
 * Platform: Linux 4.13.0-46-generic (x86_64)```

**Comment by nijel** [comment] 2019-02-21 12:30
Duplicate of #105

**Closed by nijel** 2019-02-21 12:30 UTC
Labels: bug
